name: push_notifications_trigger

on:
    workflow_dispatch:
    schedule:
        - cron: "*/5 * * * *"

jobs:
    cron:
        runs-on: ubuntu-latest

        steps:
            - name: Make push_notifications Request
              id: push_notifications_request
              uses: fjogeleit/http-request-action@v1
              with:
                  url: "https://ktu-mailer-backend.onrender.com/push_notifications?server_token=${{ secrets.SERVER_TOKEN }}"
                  method: "GET"
                  timeout: 120000
            - name: Show Response
              run: |
                  echo ${{ steps.push_notifications_request.outputs.response }}
